# render.yaml
services:
  - type: web
    name: web
    runtime: docker
    dockerfilePath: ./Dockerfile-render
    plan: free
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - fromGroup: ydidu-pdfs 
    dockerCommand: ./start.sh
